project_id = "cznakmcnmfyqmwxdtkdr"

[functions.api-endpoint]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.get-answer]
verify_jwt = false

[functions.save-llm-config]
verify_jwt = false

[functions.generate-system-prompt]
verify_jwt = false

[functions.get-google-config]
verify_jwt = false

[functions.google-drive-oauth]
verify_jwt = true

[functions.google-drive-sync]
verify_jwt = true

[functions.ai-assistant-chat]
verify_jwt = true
